### ISSUE TITLE
Feature request:  allow RPN/NRPN messages

### ISSUE THREAD

**Issue by goofy2k** [ncassetta/NiCMidi#10]
For discussion. Please let me know if I overlook a different way to implement this. 

Some sound generating devices may use use RPN/NRPN messages for special controllers. These may involve raw messages longer than 3 bytes. See e.g. [9_MIDI_code.pdf](https://github.com/ncassetta/NiCMidi/files/7827945/9_MIDI_code.pdf)
 
NiCMidi msg.cpp only deals with a max. length of 3 messages.  Access to the individual bytes goes via functions where the byte number is hard-coded (e.g. msg.GetByte1()).

To **prevent gross reorganisation** of msg.cpp and classes that use it it could be helpful to enable at least passing incoming long RPN/NRPN messages to the output. 

If the proposed approach is indeed useful, I will try to find a way to implement this. I am also implementing dealing with NRPN messages in my synth. 

[EDIT] 
- RPN and NRPN messages are part of the **General Midi standard**. These messages allow sending high resolution (14 bit) values to controllers. Using the full resolution requires sending 5-byte messages (Bn 06 data 38 data).
- I also want to comply with the **MIDI-BLE** standard. These two standards may imply that a different solution is necessary for high resolution controllers. E.g. setting a MSB and LSB in separate 3 byte messages.

**Comment by ncassetta** [comment]
I knew that an RPN or NRPN message was a set of 4 Control Change messages:
Bn 64
Bn 65   (for the parameter number)
Bn 06
Bn 26   (for data entry 14 bit)
I didn't know the existence of 5 bytes messages

**Comment by goofy2k** [comment]
See the 18th slide in this doc. With Bn 06 the message can be extended from 3 to 5 bytes by using 0x38 as the 4 th byte:
[9_MIDI_code.pdf](https://github.com/ncassetta/NiCMidi/files/7835339/9_MIDI_code.pdf)

But using 5 bytes may be not compliant with the MIDI-BLE standard:
[rp52public.pdf](https://github.com/ncassetta/NiCMidi/files/7835341/rp52public.pdf)

I will postpone this for later. So forget about the request :-)
Nevertheless it may be useful for to have the feature in you lib later (depending on the area of use of course)
