### ISSUE TITLE
'class MIDIMatrix' has no member named 'Clear'              out_matrix.Clear();

### ISSUE THREAD

**Issue by goofy2k** [ncassetta/NiCMidi#4]
I accidentally toggled the DRIVER_USES_MIDIMATRIX macro. Then the compiler complains with 

'class MIDIMatrix' has no member named 'Clear'              out_matrix.Clear();

in driver.cpp

#if DRIVER_USES_MIDIMATRIX
            out_matrix.Clear();
#endif

This is probably a non-detected bug because of hiding the code?

**Comment by ncassetta** [comment]
Yes, I renamed MIDIMatrix::Clear() into MIDIMatrix::Reset() and I miss that because the code was not compiled.
You should write out_matrix.Reset()
Thanks.

**Comment by goofy2k** [comment]
OK, I'll change that in the code.

**Comment by goofy2k** [comment]
I mean: change that in my offline code.
