### ISSUE TITLE
Compiler warning for recorder.ccp:448

### ISSUE THREAD

**Issue by goofy2k** [ncassetta/NiCMidi#5]
warning: comparison is always false due to limited range of data type [-Wtype-limits]
                         if (ch1 == ch2 || ch2 == -1)

Also (maybe related): I cannot set channel to -1 1 (or 255) in        bool                            SetTrackRecChannel(unsigned int trk_num, char chan);

This is probably NOT the cause of my problem with failure of insertion in the track (or detection that a message is IN the track).

**Comment by ncassetta** [comment]
My compiler (gcc) doesn't give me that warning. Try to cast -1 to a char or to use 0xff instead. See also my answer on the other issue

**Comment by goofy2k** [comment]
OK. This was just to let you know.

**Comment by goofy2k** [comment]
I don't see your other answer....

**Comment by ncassetta** [comment]
I answered just now.
Your warning COULD be the cause of your problem:  if the conditional at line 448 fails line 450 is not executed and  the message is not inserted into the track. You could try to substitute line 448 with 
if (true)
and see if it works

**Comment by goofy2k** [comment]
I noticed that it works even without changing this line.

The "error" fact that DumpAllTracksAtrr(sequencer.GetMultitrack(),verbose)
does not report the recorded events. When I use
DumpMidiTrackWithPauses(trk, 1)  the events are reported.

Op za 18 dec. 2021 20:47 schreef Nicola Cassetta ***@***.***>:

**Comment by goofy2k** [comment]
This issue is probably not related to issue #6.  It is just a compiler warning that may lead to unwanted behaviour when the channels have other settings than mine. I will investigate it once again and try your suggested repair.
